# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fibonacci_item <- function(n) {
    .Call(`_DemoRcpp_fibonacci_item`, n)
}

.fibonacci_seq <- function(n) {
    .Call(`_DemoRcpp_fibonacci_seq`, n)
}

.fibonacci_sum <- function(n, weights) {
    .Call(`_DemoRcpp_fibonacci_sum`, n, weights)
}
